baseURL = "https://geraldwong.net"
languageCode = "en-us"
title = "Gerald's Website"

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  mainSections = ["blog"] 
  custom_css = ["css/common.css"]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4